# Generated by Django 5.0.1 on 2024-02-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl', models.CharField(max_length=10, unique=True)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
