# Generated by Django 5.0.1 on 2024-02-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='cl',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
