# Generated by Django 5.0.1 on 2024-02-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='fee',
            field=models.PositiveIntegerField(),
        ),
    ]
