# Generated by Django 5.0.1 on 2024-02-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_studentextra_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remaining_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
