# Generated by Django 4.0 on 2024-02-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_studentextra_carryover_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='carryover_balance',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='total_due',
        ),
    ]
